app/urls.py
# -*- coding: utf-8 -*-

from .utils.helpers import HandleError
from .views import (addresses, auth, cities, deceased, doctors, graves, main,
                    registries, users, zones)


def init_app(app):
    app.register_blueprint(addresses.bp)
    app.register_blueprint(auth.bp)
    app.register_blueprint(cities.bp)
    app.register_blueprint(deceased.bp)
    app.register_blueprint(doctors.bp)
    app.register_blueprint(graves.bp)
    app.register_blueprint(main.bp)
    app.register_blueprint(registries.bp)
    app.register_blueprint(users.bp)
    app.register_blueprint(zones.bp)

    # errors
    errors = {
        403: u'Acesso Negado!',
        404: u'Página não Encontrada!',
        500: u'Erro Interno do Servidor!'
    }
    for code, message in errors.items():
        app.errorhandler(code)(HandleError('error.html', message))

app/models/doctors.py
# -*- coding: utf-8 -*-

from itertools import chain

from flask import current_app

from ..extensions import db
from ..mixins import CRUDMixin


class Doctor(CRUDMixin, db.Model):
    __tablename__ = 'doctors'
    name = db.Column(db.String(255), nullable=False)
    crm = db.Column(db.String(20), nullable=False)
    deceased = db.relationship('Deceased', backref='doctor', lazy='dynamic')

    @classmethod
    def fetch(cls, search, criteria, order, page):
        filters = ()
        columns = cls.__table__.columns.keys()
        orders = ['asc', 'desc']

        for k, v in search.items():
            if k in columns and v:
                filters += (getattr(cls, k).ilike('%' + v + '%'), )

        if criteria in columns and order in orders:
            orders = (getattr(getattr(cls, criteria), order)(), )

        return cls.query.filter(db.or_(*filters)).order_by(*orders).paginate(
            page, per_page=current_app.config['PER_PAGE'], error_out=False)

    def serialize(self):
        name = [self.name]
        if self.crm:
            name.append('CRM ' + self.crm)

        return {'id': self.id, 'name': ' - '.join(name)}

    @staticmethod
    def dump(pagination):
        headers = iter([('NOME', 'CRM')])
        data = ((d.name, d.crm) for d in pagination.query.all())
        return chain(headers, data)

    def __repr__(self):
        return '{0}({1})'.format(self.__class__.__name__, self.name)

app/forms/doctors.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import (FormField, IntegerField, SelectField, StringField,
                     SubmitField)
from wtforms.validators import InputRequired, Length

from ..utils.forms import ORDERS, get_fields


class DoctorForm(FlaskForm):
    name = StringField(
        'Nome',
        [InputRequired(message='Insira o nome do médico!'),
         Length(1, 255)])
    crm = StringField(
        'CRM',
        [InputRequired(message='Insira o CRM do médico!'),
         Length(1, 20)])
    submit = SubmitField('Salvar')


class DoctorHeadersForm(FlaskForm):
    name = StringField('Nome')
    crm = StringField('CRM')


class DoctorSearchForm(FlaskForm):
    page = IntegerField('Página', default=1)
    filters = FormField(DoctorHeadersForm)
    criteria = SelectField('Ordenar por',
                           choices=get_fields(DoctorHeadersForm),
                           default='name')
    order = SelectField('Ordem', choices=ORDERS, default='asc')

app/views/doctors.py
# -*- coding: utf-8 -*-

from flask import Blueprint, jsonify, render_template, request, url_for
from flask_login import current_user, login_required

from ..decorators import permission_required
from ..extensions import excel
from ..forms.doctors import DoctorForm, DoctorSearchForm
from ..models.doctors import Doctor

bp = Blueprint('doctors', __name__, url_prefix='/medicos')


@bp.route('/')
@login_required
def index():
    form = DoctorSearchForm(request.args)
    grid = request.args.get('grid', 0, type=bool)
    export = request.args.get('export', 0, type=int)
    filters = form.filters.data
    criteria = form.criteria.data
    order = form.order.data
    pagination = Doctor.fetch(filters, criteria, order, form.page.data)
    doctors = pagination.items
    filters = {'filters-' + k: v for k, v in filters.items()}

    if export and current_user.is_admin():
        export = Doctor.dump(pagination)
        return excel.make_response_from_array(export,
                                              'xlsx',
                                              file_name='Médicos.xlsx')

    if request.is_xhr and not grid:
        return jsonify({'result': [d.serialize() for d in doctors]})

    return render_template('doctors/index.html',
                           icon='fa-user-md',
                           title='Médicos',
                           clean_url=url_for('doctors.index'),
                           create_url=url_for('doctors.create'),
                           form=form,
                           filters=filters,
                           criteria=criteria,
                           order=order,
                           pagination=pagination,
                           doctors=doctors)


@bp.route('/adicionar', methods=['GET', 'POST'])
@login_required
@permission_required('admin')
def create():
    form = DoctorForm()

    if form.validate() and request.method == 'POST':
        doctor = Doctor()
        form.populate_obj(doctor)
        doctor.save()
        return jsonify({'redirect': url_for('doctors.index')})

    return render_template('doctors/view.html',
                           icon='fa-user-md',
                           title='Adicionar Médico',
                           form=form,
                           method='post',
                           color='success')


@bp.route('/<int:id>', methods=['GET', 'PUT'])
@login_required
def edit(id):
    view = request.args.get('format', '', type=str)
    view = True if not current_user.is_admin() else view
    title = 'Médico' if view == 'view' else 'Editar Médico'

    doctor = Doctor.get_or_404(id)
    obj = {'obj': doctor} if request.method == 'GET' else {}
    form = DoctorForm(**obj)

    if form.validate() and current_user.is_admin() and request.method == 'PUT':
        form.populate_obj(doctor)
        doctor.update()
        return jsonify({'redirect': url_for('doctors.index')})

    return render_template('doctors/view.html',
                           icon='fa-user-md',
                           title=title,
                           form=form,
                           method='put',
                           color='warning',
                           view=bool(view))


@bp.route('/<int:id>', methods=['DELETE'])
@login_required
@permission_required('admin')
def delete(id):
    Doctor.get_or_404(id).delete()
    return '', 204

app/templates/doctors/index.html
{% from '_macros.html' import render_pagination, render_modal %}
{% extends '_index.html' %}

{% block results %}
  {% for d in doctors %}
    <tr>
      <td>{{ d.name }}</td>
      <td>{{ d.crm }}</td>
      <td>
        <a href="{{ url_for('doctors.edit', id=d.id, format='view') }}" class="btn btn-raised btn-info" title="Visualizar">
          <i class="fas fa-eye"></i>
        </a>
        {% if current_user.is_admin() %}
          <a href="{{ url_for('doctors.edit', id=d.id) }}" class="btn btn-raised btn-warning" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a class="btn btn-raised btn-danger" data-delete-href="{{ url_for('doctors.delete', id=d.id) }}" onclick="app.methods.remove(this)" title="Remover">
            <i class="fas fa-trash"></i>
          </a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

{% block paginator %}
{{ render_pagination(pagination, 'doctors.index', criteria=criteria, order=order, **filters) }}
{% endblock %}

{% block dialog %}
{% call render_modal('modal-delete', 'Remover Médico', yes_text='Remover', yes_icon='trash', yes_color='danger') %}
  <p>Deseja realmente remover o Médico?</p>
{% endcall %}
{% endblock %}

app/templates/doctors/view.html
{% from '_macros.html' import render_field %}

{% extends "_view.html" %}

{% block editor %}
{{ form.csrf_token }}
{{ render_field(form.name, class_="col-md-6", autofocus=True, required=True) }}
{{ render_field(form.crm, class_="col-md-6", required=True) }}
{% endblock %}

{% block report %}
<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <th class="col-md-1">{{ form.name.label }}</th>
      <td>{{ form.name.data }}</td>
    </tr>
    <tr>
      <th class="col-md-1">{{ form.crm.label }}</th>
      <td>{{ form.crm.data }}</td>
    </tr>
  </table>
</div>
{% endblock %}