app/urls.py
# -*- coding: utf-8 -*-

from .utils.helpers import HandleError
from .views import (addresses, auth, cities, deceased, doctors, graves, main,
                    registries, users, zones)


def init_app(app):
    app.register_blueprint(addresses.bp)
    app.register_blueprint(auth.bp)
    app.register_blueprint(cities.bp)
    app.register_blueprint(deceased.bp)
    app.register_blueprint(doctors.bp)
    app.register_blueprint(graves.bp)
    app.register_blueprint(main.bp)
    app.register_blueprint(registries.bp)
    app.register_blueprint(users.bp)
    app.register_blueprint(zones.bp)

    # errors
    errors = {
        403: u'Acesso Negado!',
        404: u'Página não Encontrada!',
        500: u'Erro Interno do Servidor!'
    }
    for code, message in errors.items():
        app.errorhandler(code)(HandleError('error.html', message))

app/forms/deceased.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import (DateField, DateTimeField, FormField, IntegerField,
                     RadioField, SelectField, StringField, SubmitField)
from wtforms.validators import InputRequired, Length, Optional
from wtforms.widgets import TextArea
from wtforms.widgets.html5 import NumberInput

from ..models.addresses import Address
from ..models.cities import City
from ..models.civil_states import CivilState
from ..models.doctors import Doctor
from ..models.ethnicities import Ethnicity
from ..models.graves import Grave
from ..models.registries import Registry
from ..utils.forms import ORDERS, get_fields


class DeceasedForm(FlaskForm):
    name = StringField('Nome', [Optional(), Length(1, 255)])
    registration = StringField(
        'Matrícula do Óbito',
        [InputRequired(message='Insira a matrícula!'),
         Length(1, 40)])
    gender = RadioField('Gênero', [InputRequired(message='Insira o gênero!')],
                        choices=[('M', 'Masculino'), ('F', 'Feminino')])
    ethnicity_id = SelectField('Etnia',
                               [InputRequired(message='Insira a etnia!')],
                               choices=(),
                               coerce=int)
    civil_state_id = SelectField('Estado Civil', [Optional()],
                                 choices=(),
                                 coerce=int)
    age = IntegerField('Idade', [Optional()], widget=NumberInput(min=0))
    birth_date = DateField('Data de Nascimento', [Optional()],
                           format='%d/%m/%Y')
    birthplace_id = SelectField('Naturalidade', [Optional()],
                                choices=(),
                                coerce=int)
    filiations = StringField('Filiação', [Optional(), Length(1, 255)])
    home_city_id = SelectField('Cidade', [Optional()], choices=(), coerce=int)
    home_address_id = SelectField('Endereço Residencial', [Optional()],
                                  choices=(),
                                  coerce=int)
    home_address_number = StringField('Número', [Optional(), Length(1, 5)])
    home_address_complement = StringField(
        'Complemento', [Optional(), Length(1, 255)])
    death_datetime = DateTimeField(
        'Data de Falecimento',
        [InputRequired(message='Insira a data de falecimento!')],
        format='%d/%m/%Y %H:%M')
    death_city_id = SelectField('Cidade', [Optional()], choices=(), coerce=int)
    death_address_id = SelectField(
        'Endereço de Falecimento',
        [InputRequired('Selecione o endereço de falecimento')],
        choices=(),
        coerce=int)
    death_address_number = StringField('Número', [Optional(), Length(1, 5)])
    death_address_complement = StringField(
        'Complemento', [Optional(), Length(1, 255)])
    cause = StringField(
        'Causa da Morte',
        [InputRequired(message='Insira a causa da morte!'),
         Length(1, 1500)],
        widget=TextArea())
    zone_id = SelectField('Região', [InputRequired('Insira a região')],
                          choices=(),
                          coerce=int)
    grave_id = SelectField('Túmulo',
                           [InputRequired(message='Insira o túmulo!')],
                           choices=(),
                           coerce=int)
    doctor_id = SelectField(
        'Médico', [InputRequired(message='Insira o nome do médico!')],
        choices=(),
        coerce=int)
    registry_id = SelectField('Cartório',
                              [InputRequired(message='Insira o cartório!')],
                              choices=(),
                              coerce=int)
    annotation = StringField('Observações / Averbações',
                             [Optional(), Length(1, 1500)],
                             widget=TextArea())
    submit = SubmitField('Salvar')

    def __init__(self, *args, **kwargs):
        super(DeceasedForm, self).__init__(*args, **kwargs)
        self.ethnicity_id.choices = [(e.id, e.description)
                                     for e in Ethnicity.query.order_by(
                                         Ethnicity.description.asc()).all()]
        self.ethnicity_id.choices.insert(0, (0, ''))
        self.civil_state_id.choices = [(e.id, e.description)
                                       for e in CivilState.query.order_by(
                                           CivilState.description.asc()).all()]
        self.civil_state_id.choices.insert(0, (0, ''))

    def refill(cls):
        if cls.birthplace_id.data:
            city = City.get_or_404(cls.birthplace_id.data)
            cls.birthplace_id.choices = [tuple(city.serialize().values())]

        if cls.home_address_id.data:
            address = Address.get_or_404(cls.home_address_id.data)
            cls.home_address_id.choices = [tuple(address.serialize().values())]
            cls.home_city_id.data = address.city.id
            cls.home_city_id.choices = [
                tuple(address.city.serialize().values())
            ]

        if cls.death_address_id.data:
            address = Address.get_or_404(cls.death_address_id.data)
            cls.death_address_id.choices = [
                tuple(address.serialize().values())
            ]
            cls.death_city_id.data = address.city.id
            cls.death_city_id.choices = [
                tuple(address.city.serialize().values())
            ]

        if cls.doctor_id.data:
            doctor = Doctor.get_or_404(cls.doctor_id.data)
            cls.doctor_id.choices = [tuple(doctor.serialize().values())]

        if cls.grave_id.data:
            grave = Grave.get_or_404(cls.grave_id.data)
            cls.grave_id.choices = [tuple(grave.serialize().values())]
            if grave.zone_id:
                cls.zone_id.data = grave.zone.id
                cls.zone_id.choices = [tuple(grave.zone.serialize().values())]

        if cls.registry_id.data:
            registry = Registry.get_or_404(cls.registry_id.data)
            cls.registry_id.choices = [tuple(registry.serialize().values())]


class DeceasedHeadersForm(FlaskForm):
    name = StringField('Nome')
    birthplace_id = StringField('Naturalidade')
    death_datetime = StringField('Data de Falecimento')
    zone_id = StringField('Região')
    grave_id = StringField('Túmulo')


class DeceasedSearchForm(FlaskForm):
    page = IntegerField('Página', default=1)
    filters = FormField(DeceasedHeadersForm)
    criteria = SelectField('Ordenar por',
                           choices=get_fields(DeceasedHeadersForm),
                           default='name')
    order = SelectField('Ordem', choices=ORDERS, default='asc')

app/views/deceased.py
# -*- coding: utf-8 -*-

from flask import Blueprint, jsonify, render_template, request, url_for
from flask_login import current_user, login_required

from ..decorators import permission_required
from ..extensions import excel
from ..forms.deceased import DeceasedForm, DeceasedSearchForm
from ..models.deceased import Deceased

bp = Blueprint('deceased', __name__, url_prefix='/falecidos')


@bp.route('/')
@login_required
def index():
    form = DeceasedSearchForm(request.args)
    export = request.args.get('export', 0, type=int)
    filters = form.filters.data
    criteria = form.criteria.data
    order = form.order.data
    pagination = Deceased.fetch(filters, criteria, order, form.page.data)
    deceased = pagination.items
    filters = {'filters-' + k: v for k, v in filters.items()}

    if export and current_user.is_admin():
        export = Deceased.dump(pagination)
        return excel.make_response_from_array(export,
                                              'xlsx',
                                              file_name='Falecidos.xlsx')

    return render_template('deceased/index.html',
                           icon='fa-coffin',
                           title='Falecidos',
                           clean_url=url_for('deceased.index'),
                           create_url=url_for('deceased.create'),
                           form=form,
                           filters=filters,
                           criteria=criteria,
                           order=order,
                           pagination=pagination,
                           deceased=deceased)


@bp.route('/adicionar', methods=['GET', 'POST'])
@login_required
@permission_required('admin')
def create():
    form = DeceasedForm()
    form.refill()

    if form.validate() and request.method == 'POST':
        deceased = Deceased()
        form.populate_obj(deceased)
        deceased.save()
        return jsonify({'redirect': url_for('deceased.index')})

    return render_template('deceased/view.html',
                           icon='fa-coffin',
                           title='Adicionar Falecido',
                           form=form,
                           method='post',
                           color='success')


@bp.route('/<int:id>', methods=['GET', 'PUT'])
@login_required
def edit(id):
    view = request.args.get('format', '', type=str)
    view = True if not current_user.is_admin() else view
    title = 'Falecido' if view == 'view' else 'Editar Falecido'

    deceased = Deceased.get_or_404(id)
    obj = {'obj': deceased} if request.method == 'GET' else {}
    form = DeceasedForm(**obj)
    form.refill()

    if form.validate() and current_user.is_admin() and request.method == 'PUT':
        form.populate_obj(deceased)
        deceased.update()
        return jsonify({'redirect': url_for('deceased.index')})
    print('-' * 50)
    print(form.data)
    print(form.errors)
    print('-' * 50)

    return render_template('deceased/view.html',
                           icon='fa-coffin',
                           title=title,
                           form=form,
                           method='put',
                           color='warning',
                           view=bool(view))


@bp.route('/<int:id>', methods=['DELETE'])
@login_required
@permission_required('admin')
def delete(id):
    Deceased.get_or_404(id).delete()
    return '', 204

app/templates/deceased/index.html
{% from '_macros.html' import render_pagination, render_modal %}
{% extends '_index.html' %}

{% block results %}
  {% for d in deceased %}
    <tr>
      <td>{{ d.name }}</td>
      <td>{{ d.city.name }}</td>
      <td>{{ d.death_datetime | strftime }}</td>
      <td>{{ d.grave.zone.description }} {% if d.grave.zone.complement %} - {{ d.grave.zone.complement }}{% endif %}</td>
      <td>Rua {{ d.grave.street }} - Túmulo {{ d.grave.number }}</td>
      <td>
        <a href="{{ url_for('deceased.edit', id=d.id, format='view') }}" class="btn btn-raised btn-info" title="Visualizar">
          <i class="fas fa-eye"></i>
        </a>
        {% if current_user.is_admin() %}
          <a href="{{ url_for('deceased.edit', id=d.id) }}" class="btn btn-raised btn-warning" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a class="btn btn-raised btn-danger" data-delete-href="{{ url_for('deceased.delete', id=d.id) }}" onclick="app.methods.remove(this)" title="Remover">
            <i class="fas fa-trash"></i>
          </a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

{% block paginator %}
{{ render_pagination(pagination, 'deceased.index', criteria=criteria, order=order, **filters) }}
{% endblock %}

{% block dialog %}
{% call render_modal('modal-delete', 'Remover Falecido', yes_text='Remover', yes_icon='trash', yes_color='danger') %}
  <p>Deseja realmente remover o Falecido?</p>
{% endcall %}
{% endblock %}

app/templates/deceased/view.html
{% from '_macros.html' import render_field, render_multi_field %}

{% extends "_view.html" %}

{% block editor %}
{{ form.csrf_token }}
{{ render_field(form.name, class_="col-md-12", minlength=1, maxlength=255, autofocus=True) }}
{{ render_field(form.registration, class="number", class_="col-md-6", minlength=1, maxlength=40, required=True) }}
{{ render_multi_field(form.gender, 'radio', class_="col-md-2", required=True) }}
{{ render_field(form.ethnicity_id, class_="col-md-4", required=True) }}
{{ render_field(form.civil_state_id, class_="col-md-3") }}
{{ render_field(form.birth_date, class="date", class_="col-md-3") }}
{{ render_field(form.age, class_="col-md-1") }}
{{ render_field(form.birthplace_id, class="city", class_="col-md-5") }}
{{ render_field(form.filiations, label="bmd-label-static", class="filiation", class_="col-md-12") }}
<div class="form-row col-md-12 border">
  {{ render_field(form.home_city_id, class="city", class_="col-md-4") }}
  {{ render_field(form.home_address_id, class="address", class_="col-md-8") }}
  {{ render_field(form.home_address_number, class_="col-md-1", minlength=1, maxlength=5) }}
  {{ render_field(form.home_address_complement, class_="col-md-2") }}
</div>
{{ render_field(form.death_datetime, class="datetime", class_="col-md-3", required=True) }}
<div class="form-row col-md-12 border">
  {{ render_field(form.death_city_id, class="city", class_="col-md-4") }}
  {{ render_field(form.death_address_id, class="address", class_="col-md-8", required=True) }}
  {{ render_field(form.death_address_number, class_="col-md-1", minlength=1, maxlength=5) }}
  {{ render_field(form.death_address_complement, class_="col-md-2") }}
</div>
{{ render_field(form.cause, class_="col-md-12", maxlength=1500, required=True, rows=4) }}
{{ render_field(form.zone_id, class="zone", class_="col-md-6", required=True) }}
{{ render_field(form.grave_id, class="grave", class_="col-md-6", required=True) }}
{{ render_field(form.doctor_id, class="doctor", class_="col-md-6", required=True) }}
{{ render_field(form.registry_id, class="registry", class_="col-md-6", required=True) }}
{{ render_field(form.annotation, class_="col-md-12", maxlength=1500, rows=4) }}
{% endblock %}

{% block report %}
<div class="table-responsive">
  <table class="table table-striped table-dark lead">
    <tr>
      <th class="col-md-auto">{{ form.name.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.name.data }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.registration.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.registration.data }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.grave_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">
        <p>{{ dict(form.zone_id.choices).get(form.zone_id.data) }}</p>
        <p>{{ dict(form.grave_id.choices).get(form.grave_id.data) }}</p>
      </td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.gender.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ dict(form.gender.choices).get(form.gender.data) }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.ethnicity_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ dict(form.ethnicity_id.choices).get(form.ethnicity_id.data) }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.civil_state_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ dict(form.civil_state_id.choices).get(form.civil_state_id.data) }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.birth_date.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.birth_date.data | strftime('%d/%m/%Y') }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.age.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.age.data }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.birthplace_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ dict(form.birthplace_id.choices).get(form.birthplace_id.data) }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.filiations.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.filiations.data.replace(',', ' e ') }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.home_address_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">
        {% if form.home_address_id.data %}
        {{ dict(form.home_address_id.choices).get(form.home_address_id.data) }}, Nº {{ form.home_address_number.data }}{% if form.home_address_complement.data %} - {{ form.home_address_complement.data }}{% endif %}, {{ dict(form.home_city_id.choices).get(form.home_city_id.data) }}</td>
        {% endif %}
      </td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.death_datetime.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.death_datetime.data | strftime }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.death_address_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">
        {{ dict(form.death_address_id.choices).get(form.death_address_id.data) }}, Nº {{ form.death_address_number.data }}{% if form.death_address_complement.data %} - {{ form.death_address_complement.data }}{% endif %}, {{ dict(form.death_city_id.choices).get(form.death_city_id.data) }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.cause.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.cause.data }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.doctor_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ dict(form.doctor_id.choices).get(form.doctor_id.data) }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.registry_id.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ dict(form.registry_id.choices).get(form.registry_id.data) }}</td>
    </tr>
    <tr>
      <th class="col-md-auto">{{ form.annotation.label.text }}:</th>
      <td class="text-warning font-weight-bold">{{ form.annotation.data }}</td>
    </tr>
  </table>
</div>
{% endblock %}