app/urls.py
# -*- coding: utf-8 -*-

from .utils.helpers import HandleError
from .views import (addresses, auth, cities, deceased, doctors, graves, main,
                    registries, users, zones)


def init_app(app):
    app.register_blueprint(addresses.bp)
    app.register_blueprint(auth.bp)
    app.register_blueprint(cities.bp)
    app.register_blueprint(deceased.bp)
    app.register_blueprint(doctors.bp)
    app.register_blueprint(graves.bp)
    app.register_blueprint(main.bp)
    app.register_blueprint(registries.bp)
    app.register_blueprint(users.bp)
    app.register_blueprint(zones.bp)

    # errors
    errors = {
        403: u'Acesso Negado!',
        404: u'Página não Encontrada!',
        500: u'Erro Interno do Servidor!'
    }
    for code, message in errors.items():
        app.errorhandler(code)(HandleError('error.html', message))

app/models/zones.py
# -*- coding: utf-8 -*-

import csv
import os

from itertools import chain
from re import DOTALL, findall

from flask import current_app

from config import basedir
from ..extensions import db
from ..mixins import CRUDMixin


class Zone(CRUDMixin, db.Model):
    __tablename__ = 'zones'
    description = db.Column(db.String(40), nullable=False)
    complement = db.Column(db.String(10))
    graves = db.relationship('Grave', backref='zone', lazy='dynamic')

    @classmethod
    def fetch(cls, search, criteria, order, page):
        filters = ()
        columns = cls.__table__.columns.keys()
        orders = ['asc', 'desc']

        for k, v in search.items():
            if k in columns and v:
                if (k == 'description'
                        and findall(r'^\w+ \w+$', v, flags=DOTALL)):
                    v = v.split()
                    filters += (
                        cls.description.ilike('%' + v[0] + '%'),
                        cls.complement.ilike('%' + v[1] + '%'),
                    )
                else:
                    filters += (getattr(cls, k).ilike('%' + v + '%'), )

        if criteria in columns and order in orders:
            orders = (getattr(getattr(cls, criteria), order)(), )

        return cls.query.filter(*filters).order_by(*orders).paginate(
            page, per_page=current_app.config['PER_PAGE'], error_out=False)

    def serialize(self):
        name = [self.description]
        if self.complement:
            name.append(self.complement)
        return {'id': self.id, 'name': ' - '.join(name)}

    @classmethod
    def populate(cls):
        path = os.path.join(basedir, 'seeds', 'zones.tsv')
        with open(path) as f:
            reader = csv.DictReader(f, delimiter='\t')
            zones = [
                cls(description=row['DESCRIÇÃO'],
                    complement=row['COMPLEMENTO'])
                for row in reader
            ]
        db.session.bulk_save_objects(zones)
        db.session.commit()

    @staticmethod
    def dump(pagination):
        headers = iter([('DESCRIÇÃO', 'COMPLEMENTO')])
        data = ((z.description, z.complement) for z in pagination.query.all())
        return chain(headers, data)

    def __repr__(self):
        return '{0}({1})'.format(self.__class__.__name__, self.description)

app/forms/zones.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import (FormField, IntegerField, SelectField, StringField,
                     SubmitField)
from wtforms.validators import InputRequired, Length, Optional

from ..utils.forms import ORDERS, get_fields


class ZoneForm(FlaskForm):
    description = StringField(
        'Descrição',
        [InputRequired(message='Insira o nome da região!'),
         Length(1, 255)])
    complement = StringField('Complemento', [Optional(), Length(1, 20)])
    submit = SubmitField('Salvar')


class ZoneHeadersForm(FlaskForm):
    description = StringField('Descrição')
    complement = StringField('Complemento')


class ZoneSearchForm(FlaskForm):
    page = IntegerField('Página', default=1)
    filters = FormField(ZoneHeadersForm)
    criteria = SelectField('Ordenar por',
                           choices=get_fields(ZoneHeadersForm),
                           default='description')
    order = SelectField('Ordem', choices=ORDERS, default='asc')

app/views/zones.py
# -*- coding: utf-8 -*-

from flask import Blueprint, jsonify, render_template, request, url_for
from flask_login import current_user, login_required

from ..decorators import permission_required
from ..extensions import excel
from ..forms.zones import ZoneForm, ZoneSearchForm
from ..models.zones import Zone

bp = Blueprint('zones', __name__, url_prefix='/regioes')


@bp.route('/')
@login_required
def index():
    form = ZoneSearchForm(request.args)
    grid = request.args.get('grid', 0, type=bool)
    export = request.args.get('export', 0, type=int)
    filters = form.filters.data
    criteria = form.criteria.data
    order = form.order.data
    pagination = Zone.fetch(filters, criteria, order, form.page.data)
    zones = pagination.items
    filters = {'filters-' + k: v for k, v in filters.items()}

    if export and current_user.is_admin():
        export = Zone.dump(pagination)
        return excel.make_response_from_array(export,
                                              'xlsx',
                                              file_name='Regiões.xlsx')

    if request.is_xhr and not grid:
        return jsonify({'result': [z.serialize() for z in zones]})

    return render_template('zones/index.html',
                           icon='fa-map-marked-alt',
                           title='Regiões',
                           clean_url=url_for('zones.index'),
                           create_url=url_for('zones.create'),
                           form=form,
                           filters=filters,
                           criteria=criteria,
                           order=order,
                           pagination=pagination,
                           zones=zones)


@bp.route('/adicionar', methods=['GET', 'POST'])
@login_required
@permission_required('admin')
def create():
    form = ZoneForm()

    if form.validate() and request.method == 'POST':
        zone = Zone()
        form.populate_obj(zone)
        zone.save()
        return jsonify({'redirect': url_for('zones.index')})

    return render_template('zones/view.html',
                           icon='fa-map-marked-alt',
                           title='Adicionar Região',
                           form=form,
                           method='post',
                           color='success')


@bp.route('/<int:id>', methods=['GET', 'PUT'])
@login_required
def edit(id):
    view = request.args.get('format', '', type=str)
    view = True if not current_user.is_admin() else view
    title = 'Região' if view == 'view' else 'Editar Região'

    zone = Zone.get_or_404(id)
    obj = {'obj': zone} if request.method == 'GET' else {}
    form = ZoneForm(**obj)

    if form.validate() and current_user.is_admin() and request.method == 'PUT':
        form.populate_obj(zone)
        zone.update()
        return jsonify({'redirect': url_for('zones.index')})

    return render_template('zones/view.html',
                           icon='fa-map-marked-alt',
                           title=title,
                           form=form,
                           method='put',
                           color='warning',
                           view=bool(view))


@bp.route('/<int:id>', methods=['DELETE'])
@login_required
@permission_required('admin')
def delete(id):
    Zone.get_or_404(id).delete()
    return '', 204

app/templates/zones/index.html
{% from '_macros.html' import render_pagination, render_modal %}
{% extends '_index.html' %}

{% block results %}
  {% for z in zones %}
    <tr>
      <td>{{ z.description }}</td>
      <td>{{ z.complement }}</td>
      <td>
        <a href="{{ url_for('zones.edit', id=z.id, format='view') }}" class="btn btn-raised btn-info" title="Visualizar">
          <i class="fas fa-eye"></i>
        </a>
        {% if current_user.is_admin() %}
          <a href="{{ url_for('zones.edit', id=z.id) }}" class="btn btn-raised btn-warning" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a class="btn btn-raised btn-danger" data-delete-href="{{ url_for('zones.delete', id=z.id) }}" onclick="app.methods.remove(this)" title="Remover">
            <i class="fas fa-trash"></i>
          </a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

{% block paginator %}
{{ render_pagination(pagination, 'zones.index', criteria=criteria, order=order, **filters) }}
{% endblock %}

{% block dialog %}
{% call render_modal('modal-delete', 'Remover Região', yes_text='Remover', yes_icon='trash', yes_color='danger') %}
  <p>Deseja realmente remover a Região?</p>
{% endcall %}
{% endblock %}

app/templates/zones/view.html
{% from '_macros.html' import render_field %}

{% extends "_view.html" %}

{% block editor %}
{{ form.csrf_token }}
{{ render_field(form.description, class_="col-md-6", autofocus=True, required=True) }}
{{ render_field(form.complement, class_="col-md-6", maxlength=10) }}
{% endblock %}

{% block report %}
<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <th class="col-md-1">{{ form.description.label }}</th>
      <td>{{ form.description.data }}</td>
    </tr>
    <tr>
      <th class="col-md-1">{{ form.complement.label }}</th>
      <td>{{ form.complement.data }}</td>
    </tr>
  </table>
</div>
{% endblock %}